<a href="https://colab.research.google.com/github/jingyo-jeong/006975/blob/master/21_1_myfirst_tf_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [ ]:
import sklearn as sk
sk.__version__

'0.22.2.post1'

In [ ]:
import site
site.getsitepackages()

['/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.7/dist-packages']

In [ ]:
a, b = 10, 20

In [ ]:
a + b

30

In [ ]:
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
x.numpy()

10

In [ ]:
y = tf.constant(20)
y

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [ ]:
y.numpy()

20

In [ ]:
x + y

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
z = x + y
z

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
z.numpy()

30

In [ ]:
m = tf.constant([1, 2, 3])
m

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
m.numpy()

array([1, 2, 3], dtype=int32)

In [ ]:
tf.executing_eagerly()

True

In [ ]:
# 텐서플로 1.0 버전 선택
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

import tensorflow as tf
tf.__version__

'2.5.0'

In [ ]:
tf.executing_eagerly()

True

In [ ]:
import tensorflow as tf

hello = tf.constant('Hello World!')
print(hello)
print(hello.numpy())

tf.Tensor(b'Hello World!', shape=(), dtype=string)
b'Hello World!'


In [ ]:
a = tf.constant(5)
b = tf.constant(3)
print(a+b)
(a+b).numpy()

tf.Tensor(8, shape=(), dtype=int32)


8